### ISSUE TITLE
It's missing colorization for these...

### ISSUE THREAD

**Issue by ghost** [azat-io/atom-language-postcss#1]
Thank you for this!  Just noticed these...

Missing colorization for these CSS properties:
- align-items
- flex-grow

Missing colorization for these CSS values:
- row
- wrap

**Comment by azat-io** [comment]
@andrelima Hello! Thank you for your issue. Could you tell me the name of the plugin which is uses this syntax?

**Comment by ghost** [comment]
Yeah, those are standard CSS properties / values. Probably there are some more to add at:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes

...for Flexbox.

**Comment by ghost** [comment]
Thanks for this!
