### ISSUE TITLE
SugarSS

### ISSUE THREAD

**Issue by danielbayley** [azat-io/atom-language-postcss#12]
@azat-io I noticed you added support for _SugarSS_  in [cf06c29](https://github.com/azat-io/atom-language-postcss/commit/cf06c29b0208ee681a3af33845be9b8f1c4c3be8)…

Does that make my [language-postcss-sugarss](https://atom.io/packages/language-postcss-sugarss) package obsolete?

**Comment by danielbayley** [comment]
@azat-io If it does I'll deprecate it…

**Comment by azat-io** [comment]
Yes, I also think so
