### ISSUE TITLE
New release ruined my csscomb formatter

### ISSUE THREAD

**Issue by in-in** [azat-io/atom-language-postcss#17]
![cd22b](https://cloud.githubusercontent.com/assets/8797432/16358677/8f044086-3b23-11e6-82e8-f8270a142b8c.png)

After update i see "not supported syntax" when try lint my css.

**Comment by 2metres** [comment]
Which css-comb package are you using?

**Comment by in-in** [comment]
https://atom.io/packages/atom-css-comb

**Comment by keithjgrant** [comment]
Any notes as to why this was closed? I am seeing the same issue. atom-css-comb 3.1.0 and language-postcss v1.3.1  (assuming this did in fact work for a previous version? I haven’t used css comb before now)

**Comment by in-in** [comment]
There are no answers, and I have already stopped using csscomb.
